update init

diff --git a/tools/init b/tools/init
--- a/tools/init
+++ b/tools/init
@@ -79,8 +79,16 @@ check_env() {
 
 checkout_latest_release() {
   hash=$(git log --grep="chore(release):" -1 --pretty="%H")
-  git reset --hard "$hash"
+  
+  if [ -n "$hash" ]; then
+    echo "Found commit hash: $hash"
+    git reset --hard "$hash"
+  else
+    echo "Error: Unable to find a valid commit hash for release."
+    exit 1
+  fi
 }
+
 
 init_files() {
   if $_no_gh; then
